version: "3.7"

services:
  mongo:
    image: mongo:3.6.17-xenial
    ports:
      - "27017:27017"
    env_file:
      - .env/prod/db.env
    volumes:
      - /data/configdb:/data/configdb
      - /data/db:/data/db
    restart: always
    networks:
      - app-network

  backend:
    image: projetoales/ales_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env/prod/app.env
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/logs:/logs
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network
    command: node app.js

  frontend:
    image: projetoales/ales_frontend
    build:
      context: ./frontend
      args:
        API_URL: /api
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env/prod/ui.env
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: overlay
