version: "3.7"

services:
  mongo:
    image: mongo:3.6.17-xenial
    container_name: db
    ports:
      - "27017:27017"
    env_file:
      - .env/db.env
    volumes:
      - /data/configdb:/data/configdb
      - /data/db:/data/db
    restart: always

  mongo-express:
    image: mongo-express:0.54.0
    container_name: db_admin
    ports:
      - 8081:8081
    env_file:
      - .env/db-admin.env
    depends_on:
      - mongo
    links:
      - mongo
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ales_backend
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env/app.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - mongo-express
    restart: always
    command: yarn dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ales_frontend
    container_name: ui
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    stdin_open: true
    command: yarn start
