name: ci

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: projetoales/ales_backend:ci

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
      MONGO_HOSTNAME: ${{ secrets.MONGO_HOSTNAME }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: pull image
        run: docker pull projetoales/ales_backend:ci

      - name: run tests
        run: docker-compose -f docker-compose.ci.yml up --exit-code-from backend
